services:
  flowise:
    ports:
      - 0.0.0.0:3001:3001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  open-webui:
    ports:
      - 0.0.0.0:8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  n8n:
    ports:
      - 0.0.0.0:5678:5678
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  qdrant:
    ports:
      - 0.0.0.0:6333:6333
      - 0.0.0.0:6334:6334
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  neo4j:
    ports:
      - 0.0.0.0:7473:7473
      - 0.0.0.0:7474:7474
      - 0.0.0.0:7687:7687
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  langfuse-worker:
    ports:
      - 0.0.0.0:3030:3030
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  langfuse-web:
    ports:
      - 0.0.0.0:3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  clickhouse:
    ports:
      - 0.0.0.0:8123:8123
      - 0.0.0.0:9000:9000
      - 0.0.0.0:9009:9009
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  minio:
    ports:
      - 0.0.0.0:9010:9000
      - 0.0.0.0:9011:9001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  postgres:
    ports:
      - 0.0.0.0:5433:5432                
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  redis:
    ports:
      - 0.0.0.0:6379:6379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  searxng:
    ports:
      - 0.0.0.0:8081:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
        compress: "true"

  # ollama-cpu:
  #   ports:
  #     - 0.0.0.0:11434:11434

  # ollama-gpu:
  #   ports:
  #     - 0.0.0.0:11434:11434
      
  # ollama-gpu-amd:
  #   ports:
  #     - 0.0.0.0:11434:11434
